"""empty message

Revision ID: 456cb7e8eb47
Revises: a175d93ca219
Create Date: 2017-01-08 12:41:43.945306

"""

# revision identifiers, used by Alembic.
revision = '456cb7e8eb47'
down_revision = 'a175d93ca219'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nfl_bet_graded', sa.Column('season_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nfl_bet_graded', 'season_type')
    # ### end Alembic commands ###
