"""empty message

Revision ID: 4f07dcfe7a74
Revises: None
Create Date: 2016-09-24 19:22:46.847521

"""

# revision identifiers, used by Alembic.
revision = '4f07dcfe7a74'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('current_login_at', sa.DateTime(), nullable=True),
    sa.Column('current_login_ip', sa.String(length=45), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('away_team_bet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_key', sa.Integer(), nullable=True),
    sa.Column('bet_key', sa.Integer(), nullable=True),
    sa.Column('away_team', sa.String(length=25), nullable=True),
    sa.Column('away_ps', sa.Integer(), nullable=True),
    sa.Column('away_ml', sa.Integer(), nullable=True),
    sa.Column('amount', sa.String(), nullable=True),
    sa.Column('taken_by', sa.Integer(), nullable=True),
    sa.Column('bet_created', sa.DateTime(), nullable=True),
    sa.Column('bet_modified', sa.DateTime(), nullable=True),
    sa.Column('bet_taken', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bet_key')
    )
    op.create_table('home_team_bet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_key', sa.Integer(), nullable=True),
    sa.Column('bet_key', sa.Integer(), nullable=True),
    sa.Column('home_team', sa.String(length=25), nullable=True),
    sa.Column('home_ps', sa.Integer(), nullable=True),
    sa.Column('home_ml', sa.Integer(), nullable=True),
    sa.Column('amount', sa.String(), nullable=True),
    sa.Column('taken_by', sa.Integer(), nullable=True),
    sa.Column('bet_created', sa.DateTime(), nullable=True),
    sa.Column('bet_modified', sa.DateTime(), nullable=True),
    sa.Column('bet_taken', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bet_key')
    )
    op.create_table('over_under_bet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_key', sa.Integer(), nullable=True),
    sa.Column('bet_key', sa.Integer(), nullable=True),
    sa.Column('over_under', sa.String(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('amount', sa.String(), nullable=True),
    sa.Column('taken_by', sa.Integer(), nullable=True),
    sa.Column('bet_created', sa.DateTime(), nullable=True),
    sa.Column('bet_modified', sa.DateTime(), nullable=True),
    sa.Column('bet_taken', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bet_key')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('profile')
    op.drop_table('over_under_bet')
    op.drop_table('home_team_bet')
    op.drop_table('away_team_bet')
    op.drop_table('users')
    op.drop_table('role')
    ### end Alembic commands ###
