"""empty message

Revision ID: 6bce76e72047
Revises: c21b6eff505c
Create Date: 2016-12-17 13:03:26.292576

"""

# revision identifiers, used by Alembic.
revision = '6bce76e72047'
down_revision = 'c21b6eff505c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('TeamImg', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'TeamImg')
    # ### end Alembic commands ###
