"""empty message

Revision ID: 9d1b1d1cd471
Revises: None
Create Date: 2016-11-20 11:07:29.722144

"""

# revision identifiers, used by Alembic.
revision = '9d1b1d1cd471'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base', sa.Column('network_fees', sa.Numeric(precision=8, scale=5), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('base', 'network_fees')
    ### end Alembic commands ###
