"""empty message

Revision ID: c9dd7b8a1028
Revises: 9d1b1d1cd471
Create Date: 2016-11-25 09:33:59.754351

"""

# revision identifiers, used by Alembic.
revision = 'c9dd7b8a1028'
down_revision = '9d1b1d1cd471'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nfl_ml_bet', sa.Column('network_fees', sa.Numeric(precision=8, scale=5), nullable=True))
    op.add_column('nfl_ou_bet', sa.Column('taken_network_fees', sa.Numeric(precision=8, scale=5), nullable=True))
    op.add_column('nfl_side_bet', sa.Column('network_fees', sa.Numeric(precision=8, scale=5), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nfl_side_bet', 'network_fees')
    op.drop_column('nfl_ou_bet', 'taken_network_fees')
    op.drop_column('nfl_ml_bet', 'network_fees')
    ### end Alembic commands ###
